### ISSUE TITLE
URL Change, missing content.

### ISSUE THREAD

**Issue by coke** [Raku/doc-website#104]
Old site has

https://docs.raku.org/type/X::Proc::Async::BindOrUse

new site has

https://new-raku.finanalyst.org/type/X/Proc/Async/BindOrUse.html

And additionally, the content of the two pages seems very different.

**Comment by coke** [comment]
Discovered in review of  https://github.com/Raku/doc/issues/3773

**Comment by coke** [comment]
Would probably be fine with a rewrite rule for anything with :: that converted those to the new nested directory style.

**Comment by finanalyst** [comment]
Three separate issues here.
1. making the web page URL `/` rather than `::`. Documentable is inconsistent. Trying to mimic Documentable completely would be difficult. I think @coke 's solution of creating a re-write rule is best. In fact, there seems to be one. 
2. The non-existence of a TypeGraph. This is what #3773 was mainly about. I think that there is probably a number of webpages with missing TypeGraphs. The `typegraph` plugin for Website does not attach any SVG if the TypeGraph file does not match the webpage. In the Documentable system, there are two steps, so if no TypeGraph is available you get a 404. 
3. The content of the two files as stated **is** different. **Both** contain the content in [the pod6 source](https://github.com/Raku/doc/edit/main/doc//Type/X/Proc/Async/BindOrUse.pod6). The old site has two extra sets of information added to it: a Typegraph, and extra text from other source files. I find the extra content unsatisfactory and burdensome. I think I skipped adding it because of this personal preference, but I can try to add it in if the consensus view is that it is useful.

I do not know when Documentable began to add extra content to some source files. I think it is a relatively recent addition. Furthermore, I worry that it might create infinite loops because content is chain inserted from other sources. EG. in [old site](https://docs.raku.org/type/X::Proc::Async::BindOrUse) the content following the TypeGraph (a 404) comes from `X::Proc::Async`, which takes content from Class `Exception`.

So, the fundamental problem coming up here is about extra content being added by Documentable to source material. Before investing effort on adding this content, I would need to know:
- where the discussion about adding this extra content happened (a link to the thread would be helpful)
- when this change took place,
- does the extra content only get added to files with TypeGraphs attached to them?

**Comment by 2colours** [comment]
The URL change part has been addressed in https://github.com/Raku/doc-website/issues/149

**Comment by finanalyst** [comment]
This seems to have been resolved. Re-open with an example if it recurs.
