### ISSUE TITLE
Search missing classes

### ISSUE THREAD

**Issue by coke** [Raku/doc-website#105]
Doing a search for `Int` or `Str` for example does not have results showing the classes (or even a "Class" section at all)

`Stringy` does show the role under "Types".

I would recommend as part of the fix to move classes higher in the result list. The original site shows the int & Int classes in the first section when searching for Int, which is preferred.

**Comment by coke** [comment]
Verifying, I think this needs to be fixed before go live. Not being able to find core Types in the docs is a blocker.

**Comment by finanalyst** [comment]
The problem was a little deeper than I thought. Documentable treated Type/xxx sources slightly differently. The search candidates were included, but named differently (eg., the class Int candidate was previously named by Collection as 'type/Int' and so not given prominence by the sorting function.

The effect of the change is to introduce several more categories, such as 'class', 'role' et al. Eg., search for Dateish which is under 'Role'.

At the same time, a new category 'Composite' is added, which marks pages that contain documentation aggregated from other documentation sources.

@coke please check to see if this change meets the requirements of this issue.

**Comment by coke** [comment]
This addresses the int/Int/Str issue, thanks

**Comment by finanalyst** [comment]
closing as completed
