### ISSUE TITLE
Style issue with boxes/columns on the Programs page

### ISSUE THREAD

**Issue by coke** [Raku/doc-website#106]
https://new-raku.finanalyst.org/programs.html

The style splits the list into two columns, but ends up only having the dividing line between the 3rd and 4th items on the second column.

This makes it look like something is missing on the left hand side.

**Comment by coke** [comment]
(to be clear, this happens on all the heading pages like this, it's just very obvious when there's only the 4 items on this page)

**Comment by coke** [comment]
Linked ticket shows screenshot.

**Comment by Altai-man** [comment]
Updated the title so that it was easier to find (I did a lookup before creating the ticket and missed this one).

**Comment by finanalyst** [comment]
The solution then for Programs is to have a single column, not two columns.
This can be fixed by adding meta data to the source, and picking it up in the template.
I'll see to this in due course.

It solves the short page issue as in Programs, but not the ugly split as in Langage

**Comment by finanalyst** [comment]
@coke New UX on [new-raku](https://new-raku.finanalyst.org/programs) has a new CSS for this page.

**Comment by coke** [comment]
this is better, yes. FYI, https://new-raku.finanalyst.org/language still splits a box in the middle.

**Comment by finanalyst** [comment]
@coke I am dissatisfied with 'language', and the splitting is irritating. I want to work on that in due course. Also, I want to propose splitting language into Tutorial, General, and Reference. This follows up on an issue that Tom Browder suggested. 

When the site was powered by Documentable, it was very difficult to change. Because language is generated by `=listfiles` custom blocks, it is very easy to split the page. Look at the 'language.rakudoc' source (in the directory structure_sources).

**Comment by finanalyst** [comment]
Closing as completed
