### ISSUE TITLE
Check and upgrade highlights

### ISSUE THREAD

**Issue by JJ** [Raku/doc-website#111]
## The problem

The [highlights node library](https://www.npmjs.com/package/highlights) is used to highlight code. However, the line installing it declares its [version should be lower than 2.0](https://github.com/perl6/doc/blob/master/highlights/package.json)

That's causing some problems with the Docker build Raku/doc#2525, namely, there's some library (oniguruma) that needs to be recompiled for some reason. Adding npm rebuild to the Makefile seems to fix the problem, but still.

There are also some warnings about possible security problems. 

## Suggestions

Check with the author, @samcv , if there's a reason for that and upgrade or just use the latest if possible.

**Comment by finanalyst** [comment]
A very important issue!!!!!
The actual issue as a CSS problem has already been resolved. The relevant CSS is generated in `Website/plugins/ogdenwebb/scss/basic/_basic.scss` (I think thats the right file, it could be another one in the SCSS directory.

I want to remove the dependency on the current highlighting system altogether because:
1) it is the only part of the build process that requires `node.js`, with the entire toolchain that entails.
2) it is very bit-rotted.
3) it is inflexible, with all the syntactic categories hard coded in a haskell grammar engine that is difficult to understand
4) it was written for another purpose, namely to provide syntax highlighting for the atom IDE.
5) it requires another process to be established in the background that runs the `node.js` binary. So when highlighting happens, raku pipes a string from the rendering process to the highlighting process. Since this happens multiple times in some files, it would be best done Asynchronously. I am not convinced that it does happen asynchronously, even though some of the code is written with Async-Proc methods. In other words, I think that there is an await in the Raku code which effectively makes the run synchronous (I think, but I could be wrong, I just cant prove it). 

The problem: When a code block is encountered by the renderer (there are a couple of ways this happens), the contents is given as a string to the highlighter, which returns a string of HTML code including spans with classes that trigger CSS transformations. Only one template (code-block) is involved, so there is no need for a major refactoring of all the ProcessedPod code. 

There are several options for removing this dependency:
1. move highlighting from the build process to the browser. This means creating a Raku highlighter for a js library, such as `highlighter-js`. I have started this on the highlighter-js site. But I could not continue as I could not dedicate time to understanding node.js in order to get the module working.
  - There is also codemonitor, and @Altai-man  has put in work to get a raku module working there. 
 2. create a primitive syntax highlighter in Raku for the express purpose of highlighting for documentation.
   - I have begun work on this as well. Having gone through the pain of trying to get a js highlighter to work, I don't want to work on it again.
   - The other thing is that Raku has four slangs, something no other language has that I am aware of: Regex, Quoting, and Rakudoc (POD6) in addition to ambient code. Each of these should be treated separately, I think.
   - Finally, a Raku version should be a lot more flexible

This issue is a cleanup stage, I think,

**Comment by Altai-man** [comment]
My 2 cents on this: let's not throw away what we have working now (a feature) until we have a good replacement.

The issue is indeed important, but I believe it would be on hiatus for maybe years until we got proper rakudo-driven raku syntax highlighter. Until then, let's just use highlight.js and codemirror.js (plus it makes the code editable, double win!) as it's already something working.

I am not a huge fan of node too, for the reference.

**Comment by finanalyst** [comment]
@Altai-man highlight-js does not work because I couldn't finish the work.
Samantha McVie's highlighter still works! Just need to keep to node v14 (I think) and ignore warnings.
I'll look again at codemirror.js
Re: raku driven syntax highlighting. I don't think now we should wait for a 'proper' syntax highlighter. @jnthn has one working in Comma. A proper highlighter provides prescriptive help for a developer when code is wrong. What we want is illustrative, something to show different parts of code. This is simpler because if the regex is wrong, then it doesn't matter so much. Also, code fragments are smaller, so the context is much shorter.

**Comment by Altai-man** [comment]
>highlight-js does not work because I couldn't finish the work.

Oh yes, you're right! Yes, Samantha's highlighter was used for initial highlighting, and code-mirror does the normal one.

**Comment by finanalyst** [comment]
The original issue is resolved. Removing the node dependency requires another highlighting strategy, which is not relevant to this issue. Closing as completed.
