### ISSUE TITLE
Language overview page has inconsistent use of TM symbol

### ISSUE THREAD

**Issue by coke** [Raku/doc-website#119]
[Language ](https://docs.raku.org/language.html) - Raku appears in this overview page multiple times, inconsistently using the TM symbol.

**Comment by finanalyst** [comment]
@coke I have looked at the new website design and I cannot see the issue. Has this been fixed with the new design/tooling? If not, please give me some more information about what needs fixing.
Suggest closing this issue

**Comment by coke** [comment]
https://new-raku.finanalyst.org/language.html - Please note the inconsistent application of the TM symbol in these headers.

**Comment by finanalyst** [comment]
@coke Ok now I see.
These are **entirely ** Raku/doc issues. The titles on the language page are generated automatically from the `=TITLE` block in the relevant source files. These are respectively `Language/101-basics.pod6` and `Language/haskell-to-p6.pod6`

The only tm use in the doc-website code is the tm next to the camelia-bug icon. The tm is not in the icon image and is in the HTML. Removing it would be trivial, but I don't think that's what you mean.

**Comment by coke** [comment]
> @coke Ok now I see.
> 
> These are **entirely ** Raku/doc issues.


With the current implementation, yes. But the current setup is broken by design, and I don't think it can work as is.

I think the trademarks have to be added (or removed) as part of the build.
>

**Comment by finanalyst** [comment]
@coke I'm not in agreement with you here, but I can see your point.

My view is that the build system - such as Collection or Documentable - should be content neutral. If something is placed in content by an author, then it should be included in the rendering. I do not accept that this is 'broken by design', as I think this is a principle of design. 

In addition, Collection goes further than Documentable in separating content from rendering. Documentable generates all its index pages programmatically, eg. there is no `language.rakudoc` source. Collection expects a page to have a rakudoc source. Even the index page on doc-website, which is just a chunk of HTML code, has a rakudoc source.

Separating responsibility for content and rendering is central to Collection. In fact, I do not think Collection goes far enough. I want to create a system for having **all** user facing content, including that in the headers and footers, in rakudoc files. templates should only have format related (eg HTML tags) content. But that is an aside and it is more for my multi-language system plans.

I am in favour of consistency, which is what I think is the crux of your point. So when there is inconsistency in content, such as placing a TM after Raku, that II think) needs to be rectified in the content files. Since we have a `Raku/doc` repo, that is where the changes should be made.

Since I am opposed to have TM on one Raku and not another, I would definitely approve that sort of change. If you prefer, I could create a PR to remove it.

**However** if there is a decision - by the community or Raku/doc decision-makers - that all mentions of Raku should be accompanied by a TM, then a change can be made in relevant templates to do this. I would be happy to implement (or try to) such a policy decision. However, I would caution that there could be some consequences, as all text or all text in titles, would need to be parsed for an occurence of a Raku word. If this is done for each build, then this would lead to a performance hit, so it would still makes more sense for this to be done one-off  on the content side rather than on the build side.

**Comment by coke** [comment]
The problem is that the build system is creating new pages that don't exist in the content, and the apparent rule for the content (Only put the TM on the first item on a page) doesn't mesh with the generated pages (the indexed link might not be the one with the TM in the source)

@codesections  - can you weigh in on the use of the TM symbol in the docs? Would it be OK to have it just once in the first paragraph here: https://docs.raku.org/, and then skip it everywhere else?

**Comment by finanalyst** [comment]
@coke just saw you comment to my PR. Also @lizmat 

I suggest adding a popup to the footer, similar to the License and Generated popups, with some text about RakuTM. Actually if we only want to the text `Raku™` to appear, we could put it in the footer bar. 

I will do this now for [new-raku](new-raku.finanallyst.org). If this is OK, I'll create a PR for doc-website

**Comment by finanalyst** [comment]
I think Rakutm looks a bit lonely at the bottom of the page. Some sort of language in a popup would be nice. @codesections ??

**Comment by finanalyst** [comment]
i havent been able yet to update new-raku to show language inside popup. I have to leave for a few hours

**Comment by finanalyst** [comment]
The new suggestion for the footer can be seen on (new-raku)[new-raku.finanalyst.org]
@coke and @codesections  please look at the language in the popup box.

**Comment by coke** [comment]
Applied the PR from @finanalyst to raku/doc. Need to add some strategic TMs to the website templates.

**Comment by coke** [comment]
> Applied the PR from @finanalyst to raku/doc (removing most TMs) Need to add some strategic TMs to the website templates.

Oh. it only removed a solitary TM. more work to do here.

**Comment by coke** [comment]
Removed remaining items from raku/doc, can close this out with https://github.com/Raku/doc-website/pull/141

**Comment by finanalyst** [comment]
closing as completed with #141
