### ISSUE TITLE
can't scroll through search

### ISSUE THREAD

**Issue by coke** [Raku/doc-website#126]
searching for "int", you get more an a page worth of search results.

If you click on the scrollbar next to the search results, the popup showing the search results goes away.

If you click back in the search box, your criteria is still there, but now NO search results show.

No errors show on the console during this test.

**Comment by coke** [comment]
Note: using the scroll wheel DOES scroll the search results correctly.

**Comment by finanalyst** [comment]
@coke this is a known problem with the search-bar js. @2colours has pointed it out several times. 

We have several conversations about search-bar, and extended search.

There were issues with search-bar in the original site, @Altai-man tried to solve some, I have tried to solve some. The code relies on a jQuery catcomplete plugin, which has been highly leveraged.

There is also a search-bar issue related to the data it uses.

**Comment by finanalyst** [comment]
@Altai-man No, the change to autoComplete.js was not carried through.
I think that the patch was not applied because the Categories were not styled.
The autoComplete.js file was included as a static file, but it was never used in core.js.

I could not immediately see how to apply autoComplete. 

My first priority was to get something working as in your working site (which used catComplete), but we need a new search protocol.

I'll open a new search-bar discussion to bring all these threads together.

**Comment by coke** [comment]
> @coke this is a known problem with the search-bar js. @2colours has pointed it out several times.

Need something in the system for it to be known, which now we have.

**Comment by finanalyst** [comment]
I've opened a general discussion, so closing this issue

**Comment by coke** [comment]
Please link to the discussion.

**Comment by coke** [comment]
https://github.com/Raku/doc-website/discussions/127
