### ISSUE TITLE
Explain or change "OgdenWebb"

### ISSUE THREAD

**Issue by coke** [Raku/doc-website#16]
it's mentioned in the README and a few other places, but it's unclear what the name is supposed to mean.

**Comment by finanalyst** [comment]
The designer of the web site that @Altai-man promoted is Ogden Webb. This is included in the About page. Alexander lists himself as actively suggesting changes. Since I was developing both the legacy website UX and Altai-man's UX, I needed two names to distinguish both 'modes'. I chose the names of the web-site designers, namely MoritzLenz (for the original Raku site) and OgdenWebb (for the new one).

A name is needed for the mode to allow for other modes to be developed, eg., for an epub book.

When I first started, I called the mode 'Website'. However, I would recommend that 'Website' not be used as it may lead to confusion.

**Comment by coke** [comment]
Given that this folder name appears in the final rendered site, we should pick something more generic.

**Comment by finanalyst** [comment]
Indeed! Actually 'Website' might not be a bad name after second thoughts

**Comment by finanalyst** [comment]
Changed mode name to Website from OgdenWebb. plugin that provides styling is still called ogdenwebb, but that's not in the rendered state
