### ISSUE TITLE
Mobile/small display optimized styling

### ISSUE THREAD

**Issue by abraxxa** [Raku/doc-website#162]
## Problem

The new docs site has a great structure but currently isn‘t mobile friendly.

## Suggestions

Rework the styling to render optimized for smaller displays.

**Comment by coke** [comment]
> Hi! Have you seen https://new-raku.finanalyst.org/ ?

docs-dev.raku.org is the preferred non-prod site going forward.

> The new docs site has a great structure but currently isn‘t mobile friendly.

screen grabs calling out specific issues would be helpful, thanks. (but yes, we need to address mobile!)

**Comment by finanalyst** [comment]
@abraxxa Thanks for the feedback !!!
The new design only went live on Sunday night, and lots of problems suddenly got highlighted.

I'm very happy to start working on making the site more mobile friendly. 

As @coke just said, more specific requests / problems you encounter would help focus attention.

The CSS framework on which the site is built is Bulma, and it has extensive mobile responsiveness built in. But we have tweaked lots of things, which may have broken some of the responsiveness. So again specific issues are needed

**Comment by 2colours** [comment]
I tried today and the site *is actually surprisingly mobile friendly*. Of course, it isn't a mobile-first design AND I really really hope that will stay this way, however even the sidebar, which is kind of hacked into the layout, looks and works reasonably well.

**Comment by Altai-man** [comment]
>This site is already live according to the latest Raku blog post and the one I‘m referring to.

Can you please describe, what exactly is not mobile friendly? The new UI was developed with small screens in mind, so while I agree some things can be less than awesome, a general statement like "the whole website is not friendly / rework everything" won't get us anywhere.

**Comment by Altai-man** [comment]
Oooooh, so I have more details! CC @finanalyst

I can confirm that when accessed from mobile, the finanalyst version doesn't really work, while the original one works as intended. One of the potential reasons for the behaviour difference may be the custom footer. That's why I'm in general against of doing changes of the UI, as they may strike back at you in unexpected places.

Compare those two:

![image](https://user-images.githubusercontent.com/5764435/222135092-d659bdd9-4a20-4f61-8bf6-3104de91290b.png)

![image](https://user-images.githubusercontent.com/5764435/222135113-273c913d-a489-46e2-aa4c-e91dfd229301.png)


So I would say it's pretty critical.

**Comment by Altai-man** [comment]
Also, pay in mind it is _possible_ the dropdowns used in the new footer supposedly are not really supported in Safari browser (not sure if we want to screw Mac users).
@coke IIRC, can you confirm this claim?

I would hide the "generated from" info, it pays only to developers, and they can probably get the same info from deploy/build logs. and for users it's noise.

**Comment by coke** [comment]
buttons render OK in safari. I had asked for the generated from ages ago when it was unclear when the site had last been deployed;

I'd be fine if of the 3 buttons on the bottom:
* generated goes away and developers rely on logs (@finanalyst, this impacts work you had self assigned)
* rakuTM goes away - I've added in TMs in the top level and intro pages which cover this
* license is converted to a link, like about/toggle

**Comment by coke** [comment]
We should consider some standard sizes to support and test them on (e.g.) https://screenfly.org/ for any style changes going forward.

**Comment by finanalyst** [comment]
@Altai-man the popups are a part of the Bulma CSS on which the website relies, so it was a question only of activating them. 
The buttons were added to the full-screen version, but not the mobile one - an oversight.

Generated has always been a part of each web page, and there is actually an error in the @Altai-man templates. But I think that the generated is noise for a normal user. So ++ for removing them

RakuTM can go away if other references are sufficient.

That leaves the License. Making it into a link, rather than a popup would lead to a whole license page. That seems overkill.

**Comment by coke** [comment]
We could add a License page to the site that explains that both the content and the code are under the same license, and put the link there

**Comment by finanalyst** [comment]
@coke 
- I could create a `license.rakudoc` in `Website/source-files` 
- You could edit the License
- We could see how it looks by putting `docs-dev.raku.org/license.html` explicitly in the browser
- When the page is acceptable, change the footer entry to a link

Let me know and I'll start this.

**Comment by 2colours** [comment]
> Oooooh, so I have more details! CC @finanalyst
> 
> I can confirm that when accessed from mobile, the finanalyst version doesn't really work, while the original one works as intended. One of the potential reasons for the behaviour difference may be the custom footer. That's why I'm in general against of doing changes of the UI, as they may strike back at you in unexpected places.
> 
> Compare those two:
> 
> ![image](https://user-images.githubusercontent.com/5764435/222135092-d659bdd9-4a20-4f61-8bf6-3104de91290b.png)
> 
> ![image](https://user-images.githubusercontent.com/5764435/222135113-273c913d-a489-46e2-aa4c-e91dfd229301.png)
> 
> So I would say it's pretty critical.

And the second one is the intention? I wouldn't have imagined, that's for sure...

**Comment by finanalyst** [comment]
@coke converted License popup to link with page.
Look at [new-raku](https://new-raku.finanalyst.org) If this is OK, then i'll create a PR to move page to doc-website.

**Comment by coke** [comment]
> @coke converted License popup to link with page.
> 
> Look at [new-raku](https://new-raku.finanalyst.org) If this is OK, then i'll create a PR to move page to doc-website.

Looks good, thanks!

**Comment by Altai-man** [comment]
>And the second one is the intention? I wouldn't have imagined, that's for sure...

Yup. Smaller screens require larger controls and text which is easier to read.

**Comment by 2colours** [comment]
Well, I thought "pinch to zoom" still existed, there is no shame in using that, if you want less things to fit on your screen... Anyway, I hope we won't end up with a useless "mobile friendly" site the way Youtube, Wikipedia and many others did.

**Comment by Altai-man** [comment]
>Well, I thought "pinch to zoom" still existed, there is no shame in using that, if you want less things to fit on your screen... 

There is also a "Desktop view" option in some browsers, maybe you're aware, but I myself was very glad when I found that some time ago. :)

**Comment by 2colours** [comment]
> There is also a "Desktop view" option in some browsers, maybe you're aware, but I myself was very glad when I found that some time ago. :)

Sadly, not anymore for Youtube or Wikipedia... it's all just a so-called "mobile friendly" mess, with loads of empty spaces on the screen...

Anyway. This particular was solved with a reasonably small sacrifice, and I hope we can forget about this for good (probably not, because of the sidebar). As a rule of thumb, I don't think we should listen to the siren voices that tell us to sacrifice desktop looks in favor of outlook on the mobile. Both the userbase and the topic implies that the site will be mainly watched on desktop. If a choice needs to be made for whatever reason, let's favor the desktop.
