### ISSUE TITLE
Some .html files aren't being generated

### ISSUE THREAD

**Issue by rawleyfowler** [Raku/doc-website#181]
@dontlaugh 

For example:
https://docs.raku.org/syntax/given.html

**Comment by coke** [comment]
Changed the subject - these files don't exist at all, it's not the same as the previous issue for, e.g. /type/Int vs. /type/Int.html

**Comment by finanalyst** [comment]
@rawleyfowler Can you point me at the link that contains a reference to 'syntax/given' ? 
The secondary plugin does not generate any `/syntax` files at all. When I was reverse engineering Documentable to create secondaries, it seemed that all `syntax` data was being renamed as `routines`. So I need some information about the links to see which files it was intended for them to point at.

**Comment by 2colours** [comment]
The search tends to help with things like this: https://www.google.com/search?q=site%3Adocs.raku.org+given

And luckily we even have an archive.org save: https://web.archive.org/web/20220523025237/https://docs.raku.org/syntax/given

**Comment by 2colours** [comment]
The docs contain syntax-scoped links, an example from the control rakupod: https://github.com/Raku/doc/blob/59ffd079edc0d227ffe32ba9e12167f6fe7471b5/doc/Language/control.pod6#L661

**Comment by finanalyst** [comment]
working on the `syntax/` files. 
Lots more errors have been generated recently. @coke are there changes being made to content files?

**Comment by finanalyst** [comment]
@coke These links are the result of what seems to me to be an awful hack and bad documentation standards.

Basically, a secondary file is generated by Documentable as `syntax/filename` if and only if the header is written at `=headn X<something |Syntax,file_name>` Only a header with `X<>` markup and no other text. 

Further, there is a search for things that are considered 'syntax' when analysing other headings, but these are moved to 'routines' because of the 'syntax' hack above.

For the sake of keeping existing links, I'm making secondaries consistent. However, in the long term, the documentation needs to be edited to remove `X<>` from headings. It was an idiom adopted before HTML 2.

**Comment by finanalyst** [comment]
`syntax/` files like `syntax/role` `syntax/class`, which correspond to errors are now generated.
New content visible at [new-raku](new-raku.finanalyst.org).
Still some corner cases when Format codes are included in the markup. 
@2colours @rawleyfowler  would you see if you can find problems.
I tried to find a link to `syntax/given` as described above, but could not in current new-raku

**Comment by finanalyst** [comment]
This is mostly solved by work on the secondaries plugin that got included in PR #229.

**Comment by finanalyst** [comment]
resolved
