### ISSUE TITLE
remove redundant headings in search & Correctly represent namespace separators in the search box

### ISSUE THREAD

**Issue by cfa** [Raku/doc-website#193]
The search box represents nested packages with forward slashes rather than `::` namespace separators.

For example, searching for `AdHoc` presents `X/AdHoc` rather than `X::AdHoc` as the first hit. 

More problematically: searching for `x::adhoc` (note the casing) results in no matches; `X::AdHoc` and `x/adhoc` both match.

**Comment by finanalyst** [comment]
Definitely needed for the search-bar update. The search candidate currently may be 
- the name of a file (where `X::Y` is represented as X/Y because that is where source files are located) as mentioned in another issue, 
- the text of a heading
- the name of a routine/method/infix etc

We could changing the search candidate data so that X/Y becomes X::Y, but then we loose X/Y, unless we duplicate the entry - increasing the amount of data transferred.

Searching should be done on Uppercasing the search chars. So, not clear why there is a casing issue. Exact matches are favoured over close matches.

**Comment by finanalyst** [comment]
@cfa please test the new UI [here is an online preview](https://new-raku.finanalyst.org/language/operators).

The first `adhoc` yields the `::`, as well as `/` versions.

Case sensitive searching is dependent on the filter function.

**Comment by finanalyst** [comment]
This issue has been resolved.
@coke please review for closing the issue

**Comment by coke** [comment]
the main issue of showing X::Adhoc is fixed.

However, the remaining items are for pages like https://new-raku.finanalyst.org/routine/from-slurpy#type/X/AdHocroutinemethod

IMO, those /type links should not be part of the search results - they are just fragments of that primary page.

**Comment by finanalyst** [comment]
@coke lets close this issue then. I cant see the 'remaing items' you mentioned. Are they in another issue?
The URL you cite is a Composite page, and it relates to the way the documentation suite was first set up. There are lots of questions about Composite pages, but - I think - they deserve a discussion / issue of their own. Not this specific issue.

**Comment by coke** [comment]
No, the remaining items in the search results. search for "adhoc" and you'll see 4 results, and the last 3 should be excluded. Sorry I wasn't clear.

**Comment by finanalyst** [comment]
@coke I see the problem. When a composite file is created, the file name is put into a Heading, and from the Heading it is put as another data point in the search engine. This needs to be prevented.

**Comment by finanalyst** [comment]
@coke I have modified the 'options-search' plugin on new-raku so that headings are not included in the search data if they are in a Composite file.
Please look at new-raku because it eliminates the three 'adhoc' references.

**Comment by coke** [comment]
As I was testing this (verified the change), I found another issue: Looks like the JS is running asynchronously and if I type

`adhoc`

The search results are almost always returned in order: `a`, `ad`, `adh`, `adho`, `adhoc`, but my first attempt ended up showing the `a` results last. Having dealt with this in the past, I recommend having a dumb number to go along with each request that increases, and if an older number result comes back with the data, it's ignored because we know there's a newer set of results due. I don't think this is a blocker for merging the current set, but if not, let's log it as a separate issue.

**Comment by coke** [comment]
The main issue here is closed. I have only ever had the async issue happen to me once. Anyone else sees it, we'll open a ticket.
