### ISSUE TITLE
Add site map for SEO

### ISSUE THREAD

**Issue by JJ** [Raku/doc-website#201]
## Problem or new feature

This is simply a file that specifies the pages in the site. Good for SEO.

## Suggestions

Modify Documentable so that it generates a source map at the same time as the documentation files.

**Comment by finanalyst** [comment]
@coke @JJ @dontlaugh @Raku/core 
Here is [a rationale for site maps](https://backlinko.com/hub/seo/sitemaps)
Here is [a protocol for site maps](https://sitemaps.org/protocol.html) 
Compare with [an explanation of source maps](https://web.dev/articles/source-maps)

In principle this issue can be fairly quickly resolved by adding a Collection plugin that uses the file data accumulated during the rendering process to create a site map called `SITEMAP.XML` to be placed in the root of the rendered html directory. (There is also a `SITEMAP.TXT` file, but the difference is trivial if created as part of the build.)

There is a problem. Each URL has a mandatory tag `<loc>...</loc>`  which must contain the full domain, eg `<loc>https://docs.raku.org/introduction/</loc>`

As discussed elsewhere, the infrastructure for `Raku/doc-website` requires the rendered html to be built statically and then containerised with the Caddy webserver, but the container could be at one of several locations, eg. `https://docs.raku.org` or `https://docs-dev.raku.org`. Since SITEMAP.XML is a static file, there is no way I can see of specifying the domain at build time, or even when the container is built. (Note the original problem was resolved for the JS code because JS can detect the home domain dynamically)

So, before creating a `sitemap` plugin that operates at the report stage, I would to know how to handle the domain question. 

Possible solution: create the SITEMAP.XML for the domain `docs.raku.org`. Since the sitemap is for SEO purposes, it would only need to be available for the production site.

**Comment by coke** [comment]
I agree, I don't think we need to worry about SEO for non-prod instances.

**Comment by finanalyst** [comment]
@coke PR created. Plugin correctly creates and places `sitemap.xml`, not sure how to test SEO effectiveness.

**Comment by finanalyst** [comment]
closing as completed
