### ISSUE TITLE
ToC scrollbar hidden on Chromium

### ISSUE THREAD

**Issue by 0rir** [Raku/doc-website#215]
Moving from https://docs.raku.org/language.html
clicking on [Operators](https://docs.raku.org/language.html)
and selecting the ToC
leaves the ToC scrollbar hidden under the element upon which Camilia likes to rest.

That the scrollbar's track is invisible in the default theme leaves only the bottom down arrow as a visible clue to the bar.

For whatever it is worth, on Firefox the scrollbar fades in and out then vanishes.  I use FF little but have never noticed such behavior before.

Chromium:
Version 108.0.5359.124 (Official Build) built on Debian 11.5, running on Debian 11.6 (64-bit)

Firefox: Version 102.6.0esr (64-bit)

**Comment by 2colours** [comment]
1. Could you show a related screenshot to what you are experiencing?
2. is it intentional that you put "Operators" as another link to the language page, I thought you meant that you opened https://docs.raku.org/language/operators.html .
3. What does "selecting the ToC" mean?

**Comment by 2colours** [comment]
Thank you.

It took me a painfully long time to notice that you said "scrollbar" all along... okay, so the issue is the following: the menu bar and the side bar are competing for the same position, and for now, the menu bar simply covers the side bar. The scrollbar is right there - behind the menu bar, when you are at the top...

This has caused struggle for me as well [when I wanted to highlight ToC entries on hovering the corresponding header](https://github.com/Raku/doc-website/issues/93). With regards to broader sidebar design, perhaps there should be one solution that takes this and https://github.com/Raku/doc-website/issues/212 into account at the same time.

**Comment by 0rir** [comment]
#212 might be solved together with this.  I don't know, I've never learned much about HTML, CSS, and the later add-ons.

I do agree with @vrurg.  I forget the context, but I complained of the same.  My suggestion was to minimize the right margin, and have the left wide to hold the ToC.

**Comment by finanalyst** [comment]
@0rir Would it help if the ToC sidebar was semitransparent? That way the underlying text could be seen as well.

**Comment by finanalyst** [comment]
@0rir I have revised the HTML/CSS of the UI, introducing new sidepanels for ToC and search.

These changes hopefully address this issue. Please try the new UI and comment. [test the new UI here](https://new-raku/language/operators)

**Comment by 0rir** [comment]
This is now looking good.
