### ISSUE TITLE
Add button to copy code blocks

### ISSUE THREAD

**Issue by uzluisf** [Raku/doc-website#244]
Some code blocks are quite lengthy and having an overlaid button that copies them to the clipboard would be nice. For example, in the MDN docs (top-right corner):
![image](https://user-images.githubusercontent.com/22332927/234431354-6faa6984-b4d8-4de7-82a4-53ded2e69dee.png)
 
 Edit: I wanted to add the **UI** label to this but I cannot do it :(

**Comment by finanalyst** [comment]
@uzluisf This idea sounds interesting. Could you help implement it?
- What is the mechanism for copying? I just haven't investigated this. Is it a standard JS?
- Is it necessary to store the data separately, eg, in a hidden div?
- Once the mechanism is identified, the extra HTML code can be added to the template that renders `block-code` from Rakudoc.
- Block code is rendered in `Website/templates/02-highlighting.raku`. It should be fairly easy to add the extra code to add the mechanism.

It will a bit more complicated because there will need to be some css to fix the size and placing of the copy button. The question is where to put the css, but that's a question of style.

**Comment by finanalyst** [comment]
To add a label, click on `Labels` title in the right-hand pane. UI is one of the drop-down choices. But I'm not sure whether the functionality is only available to Maintainers.

**Comment by finanalyst** [comment]
@uzluisf  A PR has been added to doc-website.
The result can be viewed by looking at my site [new-raku](https://new-raku.finanalyst.org) where I test out changes before they are merged here.

**Comment by finanalyst** [comment]
completed
