### ISSUE TITLE
new docs break firefox/Dark Reader

### ISSUE THREAD

**Issue by doomvox** [Raku/doc-website#252]
My goal is to read light-text on a dark background, without losing the syntax highlighting colors in the code documentation.
I could do this with the Firefox "Dark Reader" extension with the old docs at raku.org, but the new setup breaks it for some reason, even though it continues to work with raku-new.finanalyst.org.

It seems strange that something about the current site setup is working differently than finanalyst.org, and this might be worth looking into.

I'm attempting to attach some screenshots, but the odds that I can drag&drop files successfully seems low.   As expected, that failed.  I pushed the  images out to my old website instead (I should open an issue, "still possible to use github with linux"):

White backgrounds at main site, in spite of Dark Reader:
![recalcitrant whiteness of the main site](http://obsidianrook.com/data/raku_docs_at_main_site.png)

The finanalyst site shows how Dark Reader is supposed to work (and used to work, with the main site):

![finanalyst.org is friendly to Dark Reader](http://obsidianrook.com/data/raku_docs_at_finanalyst_site.png)

**Comment by finanalyst** [comment]
@doomvox could you please look at [docs-dev](docs-dev.raku.org) to see if the problem persists? `docs-dev` is the site where the latest changes to the tooling are tried out. Only when everyone is happy does the newest build get pulled into `docs.raku.org`.

**Comment by doomvox** [comment]
I see the same behavior with docs-dev.

This:
https://docs.raku.org/routine/MAIN

Looks much like: 
https://docs-dev.raku.org/routine/MAIN

**Comment by finanalyst** [comment]
@doomvox Since you raised the issue, I have been battling with highlighting in Code blocks. The problem arose because of the interaction between `C<>` or `B<>` markup in Code blocks and the syntax highlighter. If you look at the operators page in new-raku, you will see towards the bottom, Bolding gets switched on, but is not cancelled.

However, just to check. Have you tested [new-raku](new-raku.finanalyst.org) recently?  I ask because there is an implementation tweak to get unicode named pages in the url. To do this, I now have the files served by Caddy behind an Apache reverse proxy. Previously new-raku was served directly by Apache, while docs-dev is served by Caddy.

Also please give a list of steps to get the Dark-Reader addon, and then how to switch on the addon. I use Firefox, but not the Dark-Reader, and I want to try to duplicate the behaviour you have.

**Comment by finanalyst** [comment]
@doomvox Jo, could you check this again please? [doc-devs.raku.org](http://docs-dev.raku.org) is now nearly the same as [new-raku](https://new-raku.finanalyst.org).

**Comment by finanalyst** [comment]
@doomvox Would you please look at the new user interface at [new-raku eg operators](https://new-raku.finanalyst.org/language/operators)

**Comment by doomvox** [comment]
> @doomvox Would you please look at the new user interface at new-raku eg operators

Dark Reader does not seem to work there.

However, it is working with:

https://docs-dev.raku.org/

**Comment by finanalyst** [comment]
@doomvox please check this again. BUT first make sure that the local storage cleared.
On Firefox, get the developers page (F12), go to storage tab, then go to local storage tab, delete all storage strings, reload.
The local storage saves your theme preference, and is saved for each domain. This may be why you are getting inconsistent results for essentially the same HTML.

**Comment by doomvox** [comment]
Okay, as far as I can tell I don't have any local cached data for the site, but I find that if I open a very old tab again I get a light background still, but if I refresh the page Dark Reader works. 

Dunno what's going on, but I'd tentatively say this is fixed, Dark Reader works now, so I'll close this.

**Comment by doomvox** [comment]
SO, let's close it.
