### ISSUE TITLE
Broken link for Empty in docs.raku.org

### ISSUE THREAD

**Issue by antononcube** [Raku/doc-website#266]
_For UI issues, please include information about your browser/resolution and a screenshot._

_For issues relating to the text of the documentation itself, please consider opening a ticket at  [Raku/doc](https://github.com/Raku/doc/issues) instead_

**Describe the bug**

Trying to go this link of `Empty` : https://docs.raku.org/syntax/Empty.html , (produces by search)

gives :

"[404: Page Not Found](https://docs.raku.org/syntax/Empty.html#404)[§](https://docs.raku.org/syntax/Empty.html#404:_Page_Not_Found)"

**To Reproduce**

https://docs.raku.org/syntax/Empty.html

3. Click on '....'
4. Scroll down to '....'
5. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by finanalyst** [comment]
@antononcube Your issue is expected and unexpected. 
1. First thing to note is that the correct URL is [docs.raku.org/syntax/Empty](http://docs.raku.org/syntax/Empty), which leads to a page. Note that there is no 'html' on the end. So in this respect, your issue is expected because the route you have given is not correct. 
2. I tried 'empty' in the search bar, and got a few candidates. None of the candidates yield a route with '.html' on the end. In this respect your issue is unexpected. I have not been able to replicate your problem using the search function on the current [docs.raku.org](https://docs.raku.org) site. 

However, there may be other ways to get a `.html` route.
1. You used a search on the older `docs.perl6.org` site. 
2. You used a URL from a blog that contained an older route. 

Some more detail is needed about how you got the route with '.html'

More generally, there are two sorts of routes, primary files and secondary files. If the route is to a primary file, then there is a physical file with a '.html' extension. So adding '.html' to the route name will yield a file that the server returns.

Since secondary files often have names that contain characters filesystems dont like, such as `/`, we use hashing tricks to get a good filename. Adding an '.html' to the URL will fail. 

Secondary files are notionally in the 'routine' and 'syntax' directories. So 'syntax/Empty' is a secondary file. 

It may be possible to slice off any '.html' on a route that is to a secondary file. Not sure if this is needed.

**Comment by finanalyst** [comment]
closing as resolved
