### ISSUE TITLE
Pod isn't rendered properly for section in the Operators page

### ISSUE THREAD

**Issue by uzluisf** [Raku/doc-website#280]
## Problem or new feature

The Pod in [circumfix [ ]](https://docs.raku.org/language/operators#Operators) isn't being rendered properly.

![image](https://github.com/Raku/doc/assets/22332927/4cb0edbf-7263-4baa-a185-bb7a1825cf7e)

[Here](https://github.com/Raku/doc/blob/main/doc/Language/operators.rakudoc#L685-L686) is the relevant line in the docs source.

## Suggestions

I'm unclear about what's going on here, I generated the HTML for that page using

```
raku --doc=HTML operators.rakudoc > output.html
```

and the Pod was rendered as expected.

**Comment by finanalyst** [comment]
@coke while this **is** a renderer bug, it's going to be a part of a major refactoring of `Raku::Pod::Render` to handle the remaining unimplemented parts of RakuDoc. 

Looking at the specific part of the documentation, there are two links to Array on the same line. The first is not rendered properly because its a `L<>` embedded in a `X<>`, and the second is a plain `L<>`. I suggest taking the first `L<>` out of the `X<>`.

Its a workaround, but looses no user information.

**Comment by finanalyst** [comment]
This issue is related to #274

**Comment by 2colours** [comment]
@finanalyst do you think this can be addressed any time soon? If not, maybe it's worth to apply a workaround of simply removing the link from the header markup.

**Comment by finanalyst** [comment]
@2colours I agree this is a very irritating bug. It is related to highlighting. I have been meaning to catch up with you about your progress on the atom-language highlighting. Part of the complexity is the way in which atom-highlighting is called to get the highlighter to work. I was hoping that you had made things a bit simpler.

**Comment by 2colours** [comment]
@finanalyst it's not obvious to me how this is related to highlighting; there should be nothing to highlight in this snippet.

Anyway, the fun is "just about to start" because we have a Textmate-style highlighter but the way it produces HTML (the Highlights JS package) is also legacy Atom code. I don't know about maintenance or alternatives; it seems to me the Pulsar project never really intended to take up on maintenance. I will look into that as well: whether Textmate grammars can be converted relatively well, an existing lib can be reasonably maintained, or a new toolchain is due.

**Comment by finanalyst** [comment]
@2colours You are right. Since this issue was raised, I have worked hard to get the `X<>` working in headings. This is using the idiom `X<L<...>|...>` which is quite rare. I just did a search on all the documents in Raku/doc
```
$ rak 'X<L<' .
Language/operators.rakudoc
689:The X<L<Array|/type/Array> constructor|Circumfix operators,Array constructor> returns an itemized L<Array|/type/Array> that does not flatten
```
So this only happens in one place.

**Comment by finanalyst** [comment]
closing as resolved by workaround
