### ISSUE TITLE
visible non-narrative anchors in operators page

### ISSUE THREAD

**Issue by stoned** [Raku/doc-website#289]
## The problem
In the operators page a lot of anchors to individual operator section are visible, non-narrative and slightly offset from the section's title.

See as examples:
- https://docs.raku.org/language/operators#index-entry-Negated_boolean_context_operator
- https://docs.raku.org/language/operators#index-entry-Negated_boolean_context_operator
- https://docs.raku.org/language/operators#index-entry-Addition_operator
- ...

This should probably be fixed, see https://github.com/Raku/doc/commit/bc233e2a3c95b18afdc044bff869bb086ebf0a8b#commitcomment-37190047

## Suggestions
- Should the anchors be made invisible and stuck to the sections' title, as in https://docs.raku.org/language/operators#index-entry-prefix_decrement_operator ?

- Should the non-narrative description of the operators be kept, as in https://docs.raku.org/language/operators#index-entry-Division_operator ?

**Comment by finanalyst** [comment]
@stoned This Issue was just transferred to the doc-website repo, which deals with the rendering of documentation sources. I have just read the issue for the first time, and I do not understand the issue. The documentation sources are now rendered by `Raku::Pod::Rendered` rather than `Pod::To::HTML` and `Documentable`.

The issue appears to be related to `X<>` instructions. This sort of markup was used originally to create anchors that were used in Table of Contents and for search purposes. However, `X<>` was intended to create Indexes or Glossaries.

**Comment by finanalyst** [comment]
@coke It seems to me that this is an issue with an older way of rendering RakuDoc to HTML and is no longer a problem. Without some more explanation as to why it might still be relevant, I propose closing the thread.
