### ISSUE TITLE
The plugin architecture's complex

### ISSUE THREAD

**Issue by dontlaugh** [Raku/doc-website#304]
A search for files named "config.raku" yields the following

```
 % fd config.raku
Website/plugins/camelia/config.raku
Website/plugins/cro-app/config.raku
Website/plugins/deprecate-span/config.raku
Website/plugins/filtered-toc/config.raku
Website/plugins/filterlines/config.raku
Website/plugins/font-awesome/config.raku
Website/plugins/gather-css/config.raku
Website/plugins/gather-js-jq/config.raku
Website/plugins/generated/config.raku
Website/plugins/hiliter/config.raku
Website/plugins/images/config.raku
Website/plugins/link-error-test/config.raku
Website/plugins/link-plugin-assets-report/config.raku
Website/plugins/listfiles/config.raku
Website/plugins/ogdenwebb/config.raku
Website/plugins/page-styling/config.raku
Website/plugins/raku-doc-setup/config.raku
Website/plugins/raku-repl/config.raku
Website/plugins/search-bar/config.raku
Website/plugins/secondaries/config.raku
Website/plugins/simple-extras/config.raku
Website/plugins/tablemanager/config.raku
Website/plugins/typegraph/config.raku
config.raku
```

This feels like a lot. Can we consolidate any of these?

**Comment by dontlaugh** [comment]
Thinking about this a bit more. Some of these functions feel very "core" to this specific website. Should any of the features that exist as plugins be hoisted into a series of normal raku modules?

**Comment by finanalyst** [comment]
@dontlaugh This is the design of `Collection`. There are three levels of configuration
1. for the whole collection, in this case all of the raku source documents,
  - The config items are how to get the source documents, which is the default Mode, etc.
2. for the `Mode`, which currently is only `Website`.
  - there is an issue to make an epub version, which I will do in due course. This will then be another `Mode`. An epub format uses XHTML not HTML, and has some specific formats for Table of Contents. So there will be new plugins for the new mode.
  - you missed the `configs/`directory in your list above
3. for each plugin.
 -  plugins provide callbacks for different stages of the build process
 - plugins config may need to specify things such as API tokens and user names (eg. for map plugins)
 - plugins config may need to give the URL for the CDN address.

The plugin system was also designed so that another plugin could be written that would be compatible with an existing one. I've done this by writing 'options-search' as a new plugin, and when we decide to change it, all that will be needed is to change the 'Mode' level config (located in the directory `Mode/configs/`).


However, I am rewriting `Raku::Pod::Render` on which Collection is built. I am rethinking plugins, so that they are defined by use statements, but I've only just started to design `RakuAST::RakuDoc::Render`.

**Comment by dontlaugh** [comment]
3 levels of config? I kind of rest my case.

> I am rethinking plugins, so that they are defined by use statements

What do you mean by this?

**Comment by finanalyst** [comment]
@dontlaugh there is a reason for this design.
If all the configuration were in one place, then you get a single registry. Make a mistake and the whole registry fails.
If configuration is associated with a fixed small set of functionality, making a mistake only affects that functionality. But the configuration is standardised, and it is tested. There is a test directory in each plugin directory, and the first test checks the configuration file.

**Comment by 2colours** [comment]
Just "for good manners" I'm posting it here as well.

Besides the basic "be nice and encouraging to the very few people who are doing anything at all (let alone most of the work)", I think it's actually a waste of resources to forcefully and deliberately reimagine the architecture of this stack.

Sure, at this point, a lot depends on Richard and Richard alone - but this needs to be compared to the state where we had nothing to work with, and I think he's done a pretty good work with explaining how certain modifications can be carried out. I personally feel that if one were to get more involved, they would get sufficient support and it wouldn't be that hard. The knowledge could be shared, it's just this site had basically less than a year in public and there were some serious challenges so the design is still not final.

And besides, we haven't made the first step. Do you have a _concrete_ idea what the architecture should look like? Because at this point I see nothing particularly actionable or estimatable.

**Comment by finanalyst** [comment]
@dontlaugh I just looked at the buildkite site, and you have a testing script for the plugins. The failure and the errors are understandable. 
This is my bad in a sense.
I develop all the plugins using another repo, and the plugins there are all test correctly. But for simplicity, and to reduce dependencies of doc-website, I have copied each plugin separately. This is documented in the original commits.
At some stage, I upgraded the test builder and renamed it. The old name was `Test::CollectionPlugin` and the new name is `Collection::TestPlugin`. Collection is already a dependency in doc-website, so name changing will not increase dependencies.
This renaming took place between the initial commit to doc-website and now.
Since the plugins weren't being tested on the doc-website, I did not update all the tests.
FWIW Had you told me you were creating the test script, I would have told you the plugins in the doc-website repo need updating.
I am trying to keep changes to a minimum. 
As far as the timing of tests, they should be triggered to changes to the plugins.

I will now create a PR to make all the changes to those plugins that need them.

**Comment by dontlaugh** [comment]
That's appreciated, but take your time. Deployment isn't blocked.

I have been spending some time with Collection over the past two days. Here's what I like:

* modular and well specified
* well-documented

It does what it says on the tin, and I don't want to rip it out. I'd merely like to explore the following: Can _any_ of the the plugins be consolidated? A lot of the tasks revolve around templating HTML.

**Comment by finanalyst** [comment]
@dontlaugh I have just completed the PR. I spent a HUUUGE amount of time in getting plugins to test, so it was just annoying that I let it slip for doc-website.
Glad to have done this, because two Collection plugins were failing tests, so got them fixed.

**Comment by finanalyst** [comment]
> Can any of the the plugins be consolidated? A lot of the tasks revolve around templating HTML.

I am constantly splitting and moving functionality between plugins. So I am certain there are better ways of doing things!!!

But the modularity is really useful. So, for example, I am changing the search function, completely rewriting the JS, but all that is needed is to write a plugin to replace 'search-bar'.  It is called 'options-search' and is in a new branch. 

All of the current plugins are related to HTML because I am focused on doc-website at present. 

As you will see, the [Collection plugins repo](https://github.com/finanalyst/collection-plugins) is structured so that under `plugins/` there is the `html/` directory. When I get around to writing a Mode to create an ebook (epub format), I will add `plugins/xhtml`

To understand some of the reasons for my design choices, take a look at the `leaflet-map` plugin. Leaflet.js is a brilliant library for getting maps from multiple tile providers onto a web page. To expose the library in a RakuDoc file, there have to be lots of configuration data.

**Comment by 2colours** [comment]
I don't know why this needed to be deleted (or whether it's even legitimate to delete comments arbitrarily) but I'm saying it again: resources could really be better spent than requesting unspecified architecture changes. Neither the accessibility of the project, nor the external interest justifies it, and in my experience it's really no issue to ask Richard for help if somebody needs to do something.

**Comment by dontlaugh** [comment]
I think I see what you're getting at.

For the pure-HTML templating case, I'm reminded of Zola's [short code system](https://www.getzola.org/documentation/content/shortcodes/). Other static site frameworks do similar things. You write a small HTML template, give it a name, drop it in the right place, and the framework handles the rest.

Other use cases are more complicated. Search is indeed one of those.

Perhaps there's a way to enable something like shortcodes without the additional executables and version system?

----

Search is an interesting case, because clearly Collection needs to generate Rakudoc and output some kind of data structure suitable for client side JS. But the surrounding `<script>` tags and larger HTML structures might not need to go through a plugin.

**Comment by finanalyst** [comment]
@dontlaugh The idea that RakuDoc's custom block could be used instead of a WordPress short-code was the inspiration. GRAV CMS uses short-codes too because GRAV uses MarkDown to create the texts. 

Originally, the idea was to only to have templates that `Raku::Pod::Render` (on which Collection is based) would use to change the RakuDoc into eg HTML. Also I designed `Raku::Pod::Render` to use other templating systems, such as Mustache and CroTml. But neither quite sufficed.
An HTML page needs both CSS and JS (and sometimes images for backgrounds), and JS libraries like Leaflet.js need API keys and tile suppliers. 
Then a collection of documents, such as the Raku suite, needs some extra glue pages and information service, such as search. 
There is another layer that I haven't yet worked on - multilingual switching. The interface elements, such as tab names, have to be in multiple languages. 
All of these led to plugins as a natural way of bundling together the various elements to enable a new Custom block to render properly.

**Comment by lizmat** [comment]
@dontlaugh could you tell us why you deleted the comment made by @2colours?

In the Raku community we only **VERY** rarely delete comments in discussions.

**Comment by dontlaugh** [comment]
@lizmat I felt they weren't really contributing. Just flaming things up. I'm sure they'd disagree, but it seems like a pattern for them.

That said, it was an overreach on my part, and it won't happen again.

----

@finanalyst I'm going to close this now, given the drama my issue caused. Not my intention.
