### ISSUE TITLE
Link on `cmp` page needs to be fixed

### ISSUE THREAD

**Issue by raiph** [Raku/doc-website#319]
If you click on the link in this text:

> See also [the documentation for the cmp operator](https://docs.raku.org/routine/cmp#(Operators)_infix_cmp).

You will arrive at a page. That page includes that same text.

It also appears in the text shown if you click on the in context link. And if you click on _that_ entry's in context link you arrive back where you started.

I suspect this is likely to be because of an underlying problem that's much more broad than just this one case I've found.

But when I searched issues for things like "link self" etc I failed to find a general issue.

**Comment by finanalyst** [comment]
@raiph @2colours I'm having trouble replicating this issue.
I clicked on the link in the first post and arrived at the composite page for `cmp`. The page lists five sources, namely 'cmp' in: type/Allomorph, type/List, type/Order, language/operators, and type/Pair.
The 'in context' links in each of those segments are correct and link without error to the relevant sections of the original documentation sources.
Please help me find which link is broken.

**Comment by 2colours** [comment]
@finanalyst it's the type/Order link, that's where @raiph 's snippet is from. And this link itself should scroll to the language/Operator part, the way the archive link does. The problem is that on the new site, the segment of the language/Operator part is `#language/operatorsroutineinfix` in the URL, while it used to be `#(Operators)_infix_cmp`.

By the way, this is quite potentially a problem with all operators. In the compound sources, their segments are all like `#language/operatorsroutineprefix` and `#language/operatorsroutineinfix`. Why is that?

**Comment by finanalyst** [comment]
@2colors I'll look at this at the weekend. It looks as if a part of the
name is missed off in the secondaries plugin, which is where composites are
generated. Or in the header template where the internal url is generated.
In the old site, sources were parsed twice, once to get composite
information then to render. New site composite information is collected at
render time. Then all composites are generated after primary sources have
been rendered.

**Comment by finanalyst** [comment]
@raiph @2colours I have looked at this issue again and I think that there may be some differences about how things should work, as opposed to how they used to work. Some comments:
1. The appearance and wording of the 'composite' pages has changed since the old site. Some of this is to reduce duplication of text, to make site navigation more intuitive, and to enhance search usability. Consequently, the lay out of the page and the links are not the same as they used to be.
2. I think the composite pages are working the way they were intended. So, if a different navigation interface is desired, please let me know.
3. I thought perhaps one of the problems is that there is a link in another source file unrelated to the ones in the cmp composite, that explicitly references `routine/cmp` and is not hitting the target. But that does not seem to be the case here.
4. The current interface for a composite file is this:
- The description contains the same text, 'compiled from sources listed below', but the search information describes the sources'
- Each segment has a title that refers to the source file
- Each title has its own link id, which is automatically generated, and is used in the TOC. This id is different to the automatic id that was generated for the old site. 
  - This is why
    > #language/operatorsroutineinfix in the URL, while it used to be #(Operators)_infix_cmp
  - All ids for heading titles are checked to be unique to the file.
- All heading titles in all documents in the site provide a 'claw' that can be used to copy the id into the paste board. This enables a writer to include that title in another completely unrelated source file.
- All heading titles in all documents also are links to the top of the file - this is a hold over from the times of HTML 1, when the TOC not in a floating side panel, and so the link was a way to get back to the top of the file and the TOC. Consequently, clicking on a heading title in a short file, where all the content is visible in the browser, does nothing.

Please let me know whether the issue here is 
- not related to the description I have just given
- not intuitive

If either of the above, please add some suggestions about how to progress this issue

**Comment by 2colours** [comment]
> Each title has its own link id, which is automatically generated, and is used in the TOC. This id is different to the automatic id that was generated for the old site.

This is the problem, I would say.

I don't think it's appropriate to chase and change all links in the source because the content generation changed - moreover, I think this should be treated - more or less... - the same way as URL's themselves. Anybody could link to these anchors anywhere, anytime. We cannot change that all. This is a "breaking change" for the site.

**Comment by raiph** [comment]
@finanalyst 

> I still can't locate where the error is.

I (@raiph) am not sure if you mean:

1. You haven't been able to locate any error related to the particular example I began this issue with.

2. You have, but haven't been able to locate where content generation is going wrong.

3. You've seen the problem I began this issue with, and have addressed that, but you've been unable to locate some *other* problem that's been mentioned in this issue discussion after my opening comment.

4. You've located some *other* problem that's been mentioned in this issue discussion after my opening comment, but haven't been able to locate the erroneous code in content generation.

I will presume it's #1. If it is, please ignore this comment.

**Comment by 2colours** [comment]
@finanalyst We have given the links that don't focus the appropriate part of the site because the #segment identifier is not what it used to be. This is not the same as a big fat 404 error; it's really just that the site should scroll to the appropriate anchors, the way the ToC also works. What else do you need to be able to reproduce it? Or maybe I should rather ask: what do you do and what behavior you get?

**Comment by 2colours** [comment]
A follow-up: https://github.com/Raku/doc-website/issues/25#issuecomment-1867094564
