### ISSUE TITLE
Miscellaneous page lacks editable tag.

### ISSUE THREAD

**Issue by 0rir** [Raku/doc-website#338]
`/miscellaneous` lacks the crayon that  allows easier pull requests.

**Comment by finanalyst** [comment]
@0rir @coke tl;dr is it worth putting a link to editable pages? Generated pages get a popup.
Detail:
There are currently 2 sorts of pages that do not get the edit crayon:
1. Composite pages, which are composed of segments from the Primary pages (those in the Raku/docs/ repo)
1. Structure pages, which are in this repo. The Miscellaneous page falls into this group.

Structure pages can be edited, via a PR on this repo, so we could set things up to allow for edits.

Composite pages cannot be edited because they are generated programmatically. So a pop-up is reasonable.

I'll create a PR to generate the pop-up. But I think we could support editing of the structure pages. Thoughts?

**Comment by finanalyst** [comment]
@coke @0rir please check out how this patch works on [new-raku, eg miscellaneous](https://new-raku.finanalyst.org/reference). Also try a composite page by using search and choosing some page.

**Comment by 0rir** [comment]
@finanalyst,  Looks good.   FYI my response time regularly can be out to a week.
