### ISSUE TITLE
Some Composite pages are not being shown/generated

### ISSUE THREAD

**Issue by finanalyst** [Raku/doc-website#346]
See issue #4433 on Raku/doc
This issue mentions 'syntax/qqx', but all `syntax/` type pages are missing.
The 'routine/' type Composite files are still being shown.
There is an unexpected difference between [docs.raku.org ... syntax/qqx](https://docs.raku.org/syntax/qqx) and [new-raku .../syntax/qqx](new-raku.finanalyst.org/syntax/qqx). I haven't figured out why or when this desynchronisation occured

**Comment by finanalyst** [comment]
@dontlaugh To solve this, I need to look at the rendered html directory. In particular there is a file called `assets/prettyurls`.

**Comment by dontlaugh** [comment]
Since the files are baked into the container, we can extract them like so (I use podman but the docker commands are almost identical)

```sh
# get latest container
podman pull quay.io/colemanx/raku-doc-website:latest
# inside the container, run "mv /usr/share/caddy /opt"
# container opt is volume mounted to my $PWD
podman run -v $PWD:/opt -it quay.io/colemanx/raku-doc-website:latest mv /usr/share/caddy /opt
# tar up result
```
[caddy.tar.gz](https://github.com/Raku/doc-website/files/14375136/caddy.tar.gz)

That's all the static files from the latest tag. Let me know if you need more @finanalyst
