### ISSUE TITLE
Extraneous text on generated page.

### ISSUE THREAD

**Issue by 0rir** [Raku/doc-website#421]
On https://docs-dev.raku.org/syntax/S%2F%2F%2F%20non-destructive%20substitution reached by a search for `s/` and selecting `s/ / /` , from  the composite options, the output's first body-line is:

     "See primary documentation in context for Lexical conventions 0"

The doc source shows nothing obvious that would create the '0'.

**Comment by finanalyst** [comment]
@0rir Sorry for the delay. Not sure how I missed these issues for so long.

If you go to [the eventual destination page for s/ / /](https://docs-dev.raku.org/language/regexes) and look at the contents panel, then restrict the content lines by typing 'lexical' in the filter bar in the contents panel, then ...  
you will find there are *two* headings with the same name. The renderer appends a `_0` to the second (`_1` to the next etc) occurrence so that a unique target is created for the URL.

So in one sense this occurs because there are two headings with the same name in the source.
But it could be seen as rendering error in that whatever the link is, it should not appear in the rendering. 
I'll fix the rendering. (It seems to be in exactly the same place as the missing '.')

**Comment by finanalyst** [comment]
closing as completed with new PR
