### ISSUE TITLE
Incomplete URLs

### ISSUE THREAD

**Issue by rafaelschipiura** [Raku/doc-website#48]
Some links are being generated without .html in the end and clicking them leads to a 404 response.

For example, the "format directives" link in https://new-raku.finanalyst.org/type/Cool.html#method_sprintf leads to https://new-raku.finanalyst.org/routine/sprintf . Adding the missing .html at the end brings the correct page.

**Comment by finanalyst** [comment]
Yes, I found this too. The behaviour may be related to that in #25

**Comment by finanalyst** [comment]
Not actually a bug. A sync issue. new-raku.finanalyst.org is generated using the distribution [raku-documentation-site](https://github.com/finanalyst/raku-documentation-site-dev), which is slightly different to [this repo](github.com/Raku/doc-website).

Whilst the infrastructure issues are being resolved for doc-website, I am updating changes on raku-documentation-site-development manually. So there may be times when there is a discontinuity.

Another slight difference can be found in the 'more' drop-down, which contains a plugins examples page. Since the plugins are related to Collection, rather than Raku, it is not included in doc-website. But it is useful for checking all the plugins are working. Eg. there is problem with fontawesome in a fresh install that doesn't exist for new-raku.finanalyst.org.

The sync errors will not happen once the Raku infrastructure is working.

**Comment by rafaelschipiura** [comment]
Ok, thank you.
