### ISSUE TITLE
Generate epub document

### ISSUE THREAD

**Issue by coke** [Raku/doc-website#75]
Similar to the old .../perl6.html page, generate a single document epub version of the docs.

**Comment by finanalyst** [comment]
I'll have a go at this. In part just to demonstrate how Collection can be used to generate different outputs from the same documents.
Note that the generation of the epub will not interfere with the generation of the website.

**Comment by dontlaugh** [comment]
Another output that would be cool: a normalized sqlite database that we could test queries on. Not to power the website, mind you, but to power other offline tools.

**Comment by finanalyst** [comment]
@dontlaugh what should be in the db? Fields etc.what sort of queries should it respond to?

**Comment by dontlaugh** [comment]
A good example might be all of the built-in classes and roles they implement. 

Something like

```sql
select c.name, r.name from classes c
join class_does_role cdr on c.class_id = cdr.role_id
join roles r on cdr.role_id = r.id
```

Basically another view into all the type information parsed from the pod files.

**Comment by finanalyst** [comment]
@dontlaugh Perhaps we can do something quite quickly without a full new Mode.

- I think, from the above, that the information required is in the table displayed in the 'Routines' tab of the website.
- Even if more information is needed, we can create a proof of concept from that table.
- The Routines page is created at the 'compilation' stage of the web site build by a plugin called ListFiles
- We can therefore create a new plugin to be triggered at the  compilation stage, say `db-creation`. This would take the data structure used by `ListFiles` (the data structure is created in the plugin `secondaries`), and output it to a data file that `sqlite` uses to create a database.
- move the database file to a place in the directory tree where it can be accessed / copied elsewhere

This is something I can do quite easily, once I know the format requirements for the sqlite input. I have done this before (used a Perl program to generate an sqlite input).

The next step would be to set up the infrastructure that
- takes the database file from a 
- instantiates an sql database
- receives a query (presumably through via the Internet), serves the response.
This task is beyond me at the present because I do not know how you might want to host this.
- Another docker container?
- Using Caddy in some way?

**Comment by finanalyst** [comment]
I have begun work on an EBook mode.
@coke @dontlaugh some questions and comments:
1. would it be possible to grant me commit rights without review for a week or so? 
   - Only for a new directory `EBook`. If I make changes to the Website (as in a button to download), I would create a PR for review.
   - Once the new mode is meeting tests, we can go back to the current scheme.
3. The aim would be for the ebook, in a file called **RakuDocumentation.epub** (or something) to be generated into a directory allowing for a download. 
  - is this a good name? 
4. We would need to change the docs.raku.org index page to have a button that starts a download.
  - the directory that the epub file ends in should be inside the docker container 
  - what to call the directory **e-book/** ?
5. A significant number of resources needed to generate the Website would be also used to generate the ebook, so it would make sense to have them generated at the same time. 
  - would this cause a problem?

**Comment by coke** [comment]
> I have begun work on an EBook mode.
> @coke @dontlaugh some questions and comments:
> 
> would it be possible to grant me commit rights without review for a week or so?
> Only for a new directory EBook. If I make changes to the Website (as in a button to download), I would create a PR for review.
> Once the new mode is meeting tests, we can go back to the current scheme.

Would it make sense to do the work in a branch instead?

> The aim would be for the ebook, in a file called RakuDocumentation.epub (or something) to be generated into a directory allowing for a download.
> is this a good name?

This is fine.

> We would need to change the docs.raku.org index page to have a button that starts a download.

+1

> the directory that the epub file ends in should be inside the docker container
> what to call the directory e-book/ ?

epub?

> A significant number of resources needed to generate the Website would be also used to generate the ebook, so it would make sense to have them generated at the same time.
> would this cause a problem?

Makes sense to me to have them updated at the same time.

**Comment by coke** [comment]
Also: Thanks for tackling this!

**Comment by dontlaugh** [comment]
> would it be possible to grant me commit rights without review for a week or so?

No, let's not do this. But I have a compromise: I will change the automatic deployment of docs-dev.raku.org in the following ways:

* It will build from a branch called, say, `docs-dev`. You will be able to push to this at will.
* I will make the frequency of the automatic deployment more aggressive. Perhaps every 30 minutes. This will give you faster feedback.

Give me 24-48 hours for this. I will comment on this issue with more details when it's done.

Otherwise, your plan sounds good 👍. 

If you focus on generating the epub first, I can look into the Caddy server config that lets us do this "correctly" from a web standards point of view: responding with the correct MIME type headers, for instance. We also definitely want downloading to work with pure `curl`, even if the website requires JavaScript.

**Comment by finanalyst** [comment]
@dontlaugh the compromise is better! I need something to test in situ, but I don't want to affect the main branch until we have things working.

**Comment by dontlaugh** [comment]
The server automation is almost done. Here is what happens next.

* PR #355 gets merged to main; go take a look at that
* @finanalyst create a new branch called "docs-dev" off of main
* Push your docs-dev branch to github

https://docs-dev.raku.org is already configured to pull a "docs-dev"-tagged container image from quay. I cloned latest for the first one. https://quay.io/repository/colemanx/raku-doc-website?tab=tags

Every push to docs-dev will build/push/overwrite the docs-dev tag on quay

Every 30 minutes that container gets deployed to docs-dev

**Comment by dontlaugh** [comment]
@finanalyst we should be good to go. Pull down the `docs-dev` branch and then make any commits you want, push it back up, and every 30 minutes the the (current) docs-dev container tag will be deployed.

**Comment by finanalyst** [comment]
@dontlaugh I pulled the git repo and found docs-dev. I changed to the branch and added directories and files. When I went to commit I got a message that I have a detached head. 
I'm not sure how to proceed. Do I go ahead with the commit? Do I have to fix the detached head in my local repo?

**Comment by coke** [comment]
Sounds like you checked out the commit of the branch instead of the branch itself?

I would, if it's not too much trouble, start over with:

```
$ git clone git@github.com:Raku/doc-website.git
$ cd doc-website
$ git checkout -b docs-dev
```
Then in this state `git add` (note you cannot add directories, only files), and finally `git commit` and `git push`.

You might want to try this just with one file to make sure you haven't missed anything.

I'm sure it's possible to fixup the clone you already have but without a screen share it will be tedious.

**Comment by dontlaugh** [comment]
@finanalyst It is difficult to give precise advice here without knowing about the state of your local repository, and what your local changes are. I don't want to make you lose your work.

Paste the output of `git status` in a comment and it will give me a better idea of what's up.

**Comment by finanalyst** [comment]
@dontlaugh 
> Another output that would be cool: a normalized sqlite database that we could test queries on. Not to power the website, mind you, but to power other offline tools.

Would you create a separate issue for this. I have started thinking about this but it is different to the epub issue, which I have also started on.

By the way, thanks for pointing to the reddit thread as it showed I needed to work on the epub.

**Comment by finanalyst** [comment]
Closing as this is being tracked in #356
