### ISSUE TITLE
https://new-raku.finanalyst.org/type.html vs. https://new-raku.finanalyst.org/types.html

### ISSUE THREAD

**Issue by coke** [Raku/doc-website#87]
These appear to be the same content with wildly different formatting.

**Comment by finanalyst** [comment]
> with wildly different formatting
The whole web design is mostly the same content with wildly different formatting. 

We four different formats, the site as per 
- docs.raku.org
- raku.finanalyst.org ( an attempt to mimic and improve on the above )
- [Altai-man's redesign, cant remember the IP] aka OgdenWebb
- new-raku.finanalyst.org ( using the OgdenWebb design using Collection )

The aim of the types page with new-raku was to keep to the same overall design as the Language page of the OgdenWebb design. It also uses a simplified definition of the page in Rakudoc, rather than generating it entirely from a template. That makes it easier to modify without breaking the page.

So which of the different user pages is preferable? The content in each is the same.

**Comment by finanalyst** [comment]
Ignore previous comment! Written without reading the title correctly. 
`type.html` is an rsync error. I made a typo and generated type.html instead of types.html. The old file continued to exist. 'type.html' purged from the server. 

Type.html should not be generated from sources in current doc-website repo.

Closing this issue as fixed
